[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "spotss"
authors = [{name = "ljc", email = "123@lumache"}]
dynamic = ["version", "description"]
